# Generated by Django 4.1.3 on 2022-11-15 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("album_id", models.IntegerField()),
                ("title", models.CharField(help_text="photo title", max_length=240)),
                ("width", models.IntegerField(help_text="photo width", null=True)),
                ("height", models.IntegerField(help_text="photo height", null=True)),
                (
                    "dominant_color",
                    models.CharField(
                        help_text="photo dominant color in hex format",
                        max_length=7,
                        null=True,
                    ),
                ),
                ("URL", models.ImageField(null=True, upload_to="")),
            ],
        ),
    ]
