# Generated by Django 4.1.3 on 2022-11-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="URL",
            field=models.ImageField(
                help_text="URL to locally stored file", null=True, upload_to=""
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="album_id",
            field=models.IntegerField(help_text="Album ID"),
        ),
        migrations.AlterField(
            model_name="photo",
            name="dominant_color",
            field=models.CharField(
                help_text="Photo dominant color in hex format", max_length=7, null=True
            ),
        ),
        migrations.AlterField(
            model_name="photo",
            name="height",
            field=models.IntegerField(help_text="Photo height", null=True),
        ),
        migrations.AlterField(
            model_name="photo",
            name="title",
            field=models.CharField(help_text="Photo title", max_length=240),
        ),
        migrations.AlterField(
            model_name="photo",
            name="width",
            field=models.IntegerField(help_text="Photo width", null=True),
        ),
    ]
