# Generated by Django 4.1.3 on 2022-11-13 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("photo", "0002_alter_photo_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="photo",
            name="external_photo_URL",
        ),
    ]
