# Generated by Django 4.1.3 on 2022-11-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photo", "0002_alter_photo_url_alter_photo_album_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="URL",
            field=models.URLField(help_text="URL to locally stored file", null=True),
        ),
    ]
