# Generated by Django 4.1.3 on 2022-11-14 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photo", "0003_remove_photo_external_photo_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
