# Generated by Django 4.1.3 on 2022-11-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photo", "0004_alter_photo_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="external_URL",
            field=models.URLField(help_text="external URL", null=True),
        ),
    ]
