# Generated by Django 4.1.3 on 2022-11-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Photo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("album_id", models.IntegerField(help_text="Album ID")),
                ("title", models.CharField(help_text="Photo title", max_length=240)),
                ("width", models.IntegerField(help_text="Photo width", null=True)),
                ("height", models.IntegerField(help_text="Photo height", null=True)),
                (
                    "dominant_color",
                    models.CharField(
                        help_text="Photo dominant color in hex format",
                        max_length=7,
                        null=True,
                    ),
                ),
                (
                    "URL",
                    models.ImageField(
                        help_text="URL to locally stored file", null=True, upload_to=""
                    ),
                ),
                ("external_URL", models.URLField(help_text="external URL", null=True)),
            ],
        ),
    ]
